spring.application.name=multitenant-saas
server.port=8082
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD:admin123}
logging.level.com.nadir=DEBUG
